### ISSUE TITLE
ConcurrentModificationException in ActionProvider during functional tests

### ISSUE THREAD

**Issue by Voycawojka** [Knotx/knotx-fragments#114]
**Describe the bug**
Running a `KnotxFragmentsDebugDataWithHandlebarsTest#requestPage` test results in an exception thrown and therefore a failed test. Seems to only happen when run through IntelliJ on Windows.

**To Reproduce**
1. Open IntelliJ
2. Go to `KnotxFragmentsDebugDataWithHandlebarsTest` file
3. Run `requestPage` test

**Expected behavior**
Test passes

**Stacktrace**
```
2020-03-06 14:30:15.054 [vert.x-eventloop-thread-1] DEBUG i.k.fragments.handler.TaskProvider - Task factory [default] accepts fragment [7d516fe9-26c5-449c-a6e3-466168de86a2]
2020-03-06 14:30:15.071 [vert.x-eventloop-thread-1] DEBUG i.k.fragments.handler.TaskProvider - Task factory [default] accepts fragment [f9a141f0-b2af-40d3-874f-a30ccf6cd1fd]
2020-03-06 14:30:15.094 [vert.x-eventloop-thread-1] TRACE i.v.e.w.impl.RoutingContextImplBase - Throwable thrown from handler
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at io.knotx.fragments.task.factory.node.action.ActionProvider.get(ActionProvider.java:69)
	at io.knotx.fragments.task.factory.node.action.ActionNodeFactory.initNode(ActionNodeFactory.java:77)
	at io.knotx.fragments.task.factory.DefaultTaskFactory.lambda$initNode$2(DefaultTaskFactory.java:104)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.knotx.fragments.task.factory.DefaultTaskFactory.initNode(DefaultTaskFactory.java:104)
	at io.knotx.fragments.task.factory.node.subtasks.SubtasksNodeFactory.lambda$initNode$0(SubtasksNodeFactory.java:66)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.knotx.fragments.task.factory.node.subtasks.SubtasksNodeFactory.initNode(SubtasksNodeFactory.java:67)
	at io.knotx.fragments.task.factory.DefaultTaskFactory.lambda$initNode$2(DefaultTaskFactory.java:104)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.knotx.fragments.task.factory.DefaultTaskFactory.initNode(DefaultTaskFactory.java:104)
	at io.knotx.fragments.task.factory.DefaultTaskFactory.lambda$initTransitions$4(DefaultTaskFactory.java:118)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at io.knotx.fragments.task.factory.DefaultTaskFactory.initTransitions(DefaultTaskFactory.java:117)
	at io.knotx.fragments.task.factory.DefaultTaskFactory.lambda$initNode$2(DefaultTaskFactory.java:104)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.knotx.fragments.task.factory.DefaultTaskFactory.initNode(DefaultTaskFactory.java:104)
	at io.knotx.fragments.task.factory.DefaultTaskFactory.lambda$newInstanceWithMetadata$0(DefaultTaskFactory.java:89)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.knotx.fragments.task.factory.DefaultTaskFactory.newInstanceWithMetadata(DefaultTaskFactory.java:87)
	at io.knotx.fragments.handler.TaskProvider.lambda$newInstance$2(TaskProvider.java:55)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.knotx.fragments.handler.TaskProvider.newInstance(TaskProvider.java:55)
	at io.knotx.fragments.handler.ExecutionPlan.getTaskWithMetadataFor(ExecutionPlan.java:45)
	at java.base/java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1659)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.knotx.fragments.handler.ExecutionPlan.<init>(ExecutionPlan.java:23)
	at io.knotx.fragments.handler.FragmentsHandler.handle(FragmentsHandler.java:67)
	at io.knotx.fragments.handler.FragmentsHandler.handle(FragmentsHandler.java:42)
	at io.vertx.reactivex.ext.web.api.contract.openapi3.OpenAPI3RouterFactory$8.handle(OpenAPI3RouterFactory.java:259)
	at io.vertx.reactivex.ext.web.api.contract.openapi3.OpenAPI3RouterFactory$8.handle(OpenAPI3RouterFactory.java:257)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:95)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
	at io.vertx.reactivex.ext.web.RoutingContext.next(RoutingContext.java:123)
	at io.knotx.server.api.handler.DefaultRequestContextEngine.next(DefaultRequestContextEngine.java:70)
	at io.knotx.server.api.handler.DefaultRequestContextEngine.processAndSaveResult(DefaultRequestContextEngine.java:43)
	at io.knotx.fragments.supplier.api.FragmentsSupplierHandler.handle(FragmentsSupplierHandler.java:57)
	at io.knotx.fragments.supplier.api.FragmentsSupplierHandler.handle(FragmentsSupplierHandler.java:31)
	at io.vertx.reactivex.ext.web.api.contract.openapi3.OpenAPI3RouterFactory$8.handle(OpenAPI3RouterFactory.java:259)
	at io.vertx.reactivex.ext.web.api.contract.openapi3.OpenAPI3RouterFactory$8.handle(OpenAPI3RouterFactory.java:257)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:95)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
	at io.vertx.reactivex.ext.web.RoutingContext.next(RoutingContext.java:123)
	at io.knotx.server.api.handler.DefaultRequestContextEngine.next(DefaultRequestContextEngine.java:70)
	at io.knotx.server.api.handler.DefaultRequestContextEngine.processAndSaveResult(DefaultRequestContextEngine.java:43)
	at io.knotx.server.api.handler.reactivex.RequestEventHandler.lambda$handle$0(RequestEventHandler.java:47)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onSuccess(SingleResumeNext.java:65)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:60)
	at io.vertx.reactivex.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:49)
	at io.vertx.reactivex.ext.web.client.HttpRequest$10.handle(HttpRequest.java:621)
	at io.vertx.reactivex.ext.web.client.HttpRequest$10.handle(HttpRequest.java:618)
	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:308)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:295)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:270)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:267)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:277)
	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:238)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$2(HttpContext.java:367)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-06 14:30:15.094 [vert.x-eventloop-thread-1] TRACE i.v.e.w.impl.RoutingContextImplBase - Failing the routing
2020-03-06 14:30:15.107 [Test worker] INFO  o.e.j.s.NetworkTrafficServerConnector - Stopped NetworkTrafficServerConnector@68053111{HTTP/1.1}{0.0.0.0:63484}
2020-03-06 14:30:15.108 [Test worker] INFO  o.e.j.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@72b530dc{/,null,UNAVAILABLE}
2020-03-06 14:30:15.109 [Test worker] INFO  o.e.j.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@200745ae{/__admin,null,UNAVAILABLE}
2020-03-06 14:30:15.110 [Test worker] WARN  o.e.j.util.thread.QueuedThreadPool - qtp103872894{STOPPING,8<=8<=10,i=5,q=5} Couldn't stop Thread[qtp103872894-59,5,]
2020-03-06 14:30:15.110 [Test worker] WARN  o.e.j.util.thread.QueuedThreadPool - qtp103872894{STOPPING,8<=8<=10,i=0,q=5} Couldn't stop Thread[qtp103872894-65,5,]

org.opentest4j.AssertionFailedError: expected: <200> but was: <500>
java.lang.AssertionError: org.opentest4j.AssertionFailedError: expected: <200> but was: <500>
	at io.vertx.junit5.VertxExtension.joinActiveTestContexts(VertxExtension.java:226)
	at io.vertx.junit5.VertxExtension.afterTestExecution(VertxExtension.java:197)
	at io.knotx.junit5.KnotxExtension.afterTestExecution(KnotxExtension.java:157)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterTestExecutionCallbacks$8(TestMethodTestDescriptor.java:221)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$12(TestMethodTestDescriptor.java:256)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:256)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:255)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterTestExecutionCallbacks(TestMethodTestDescriptor.java:220)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.opentest4j.AssertionFailedError: expected: <200> but was: <500>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
	at io.knotx.stack.functional.KnotxFragmentsDebugDataWithHandlebarsTest.responseShouldBeValid(KnotxFragmentsDebugDataWithHandlebarsTest.java:114)
	at io.knotx.stack.functional.KnotxFragmentsDebugDataWithHandlebarsTest.lambda$knotxShouldProvideDebugData$0(KnotxFragmentsDebugDataWithHandlebarsTest.java:108)
	at io.knotx.stack.KnotxServerTester.lambda$testGet$3(KnotxServerTester.java:95)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:54)
	at io.vertx.reactivex.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:49)
	at io.vertx.reactivex.ext.web.client.HttpRequest$10.handle(HttpRequest.java:621)
	at io.vertx.reactivex.ext.web.client.HttpRequest$10.handle(HttpRequest.java:618)
	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:308)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:295)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:270)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:267)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:277)
	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:238)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$2(HttpContext.java:367)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more


```

**Comment by Skejven** [comment]
@Voycawojka which version of JDK do you use in the project?
